"""
constants.py

A file containing constant values used throughout the application
"""

import logging

from aws_model import InstanceFilter

DEFAULT_ALL_FILTER: InstanceFilter = InstanceFilter("*** All Instances ***", [[]])


# State machine states
STATE_GRACEFUL_EXIT = -1.0
STATE_READ_SETTINGS_FILE = 1.0
STATE_VALIDATE_SETTINGS = 2.0
STATE_READ_PROFILES_FILE = 3.0
STATE_SHOW_NO_PROFILES_FOUND = 4.0
STATE_VALIDATE_PROFILE_CONNECTIVITY = 5.0
STATE_INITIALIZE_SESSION_OBJECT = 6.0
STATE_SHOW_PROFILE_SELECTOR = 7.0
STATE_SHOW_REGION_SELECTOR = 9.0
STATE_SHOW_INSTANCE_FILTER_SELECTOR = 11.0
STATE_SHOW_INSTANCE_SELECTOR = 13.0
STATE_POPULATE_INSTANCE_RESULTS = 15.0
STATE_SHOW_CONFIGURATOR = 16.0
STATE_START_SSM_TERMINAL_SESSION = 17.0
STATE_SHOW_PORT_SELECTOR = 18.0
STATE_VALIDATE_PORT_AVAILABILITY = 19.0
STATE_SHOW_PORT_OCCUPIED_DIALOG = 20.0
STATE_START_SSM_PORT_FORWARDING_SESSION = 22.0
STATE_LOAD_REGION = 23.0
STATE_LOAD_INSTANCE_RESULTS = 24.0
STATE_HANDLE_LOAD_INSTANCE_RESULTS_ERROR = 25.0
STATE_SET_DEFAULT_INSTANCE = 26.0


# DIALOG outputs
DIALOG_YES = "Yes"
DIALOG_NO = "No"
DIALOG_CONFIRM = "Confirm"
DIALOG_BACK = "Back"
DIALOG_QUIT = "Quit"
DIALOG_SELECT = "Select"
DIALOG_CANCEL = "Cancel"
DIALOG_CONNECT = "Connect"

DIALOG_PROFILE = "PROFILE"
DIALOG_REGION = "REGION"
DIALOG_FILTER = "FILTER"
DIALOG_INSTANCE = "INSTANCE"

DIALOG_NON_ACTIVE_PROFILE = "NON_ACTIVE_PROFILE"

TASK_SUCCESS = "Success"
TASK_ERROR = "Error"

DEFAULT_LOCAL_PORT = "9999"
DEFAULT_REMOTE_PORT = "22"

SSM_MODE_IN_TERMINAL = "terminal"
SSM_MODE_PORT_FORWARDING = "port-forwarding"

LOGGING_VALUE_MAP = {
    "CRITICAL": logging.CRITICAL,
    "FATAL": logging.FATAL,
    "ERROR": logging.ERROR,
    "WARNING": logging.WARNING,
    "WARN": logging.WARNING,
    "INFO": logging.INFO,
    "DEBUG": logging.DEBUG,
    "NOTSET": logging.NOTSET,
}
